version: "3"

services:
  backend:
    build: .
    volumes:
      - ./:/usr/app/
    working_dir: /usr/app
    command: sh -c 'alembic upgrade head && python -m app'
    networks:
      - app-network
    env_file:
      - ./.env
    depends_on:
      - database
      - redis

  database:
    image: postgres:latest
    container_name: database_container
    restart: always
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - app-network
    ports:
      - "25432:5432"

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - app-network
    ports:
      - "6379:6379"

networks:
    app-network: